version: '3'

services:
  code_assistent:
    build: .
    container_name: code_assistent
    ports:
      - "8051:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=code-assistent.settings
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume: