# Generated by Django 5.1.3 on 2024-11-11 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='título', default='', max_length=255, verbose_name='título')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='conversa_chat', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_chat', to=settings.AUTH_USER_MODEL, verbose_name='Conversa de chat')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(db_column='chat', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chatbot.conversationchat', verbose_name='chat')),
            ],
        ),
    ]
